; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main_node

[env:main_node]
platform = espressif32@7.0.1
board =  adafruit_feather_esp32s3_nopsram
upload_port = COM17
framework = arduino
lib_deps = h2zero/NimBLE-Arduino@^1.0.0
	adafruit/Adafruit NeoPixel@^1.12.0
	adafruit/Adafruit MAX1704X@^1.0.3
	bblanchon/ArduinoJson@^6.20.2
build_flags = 
	-DMAIN_NODE
	-std=gnu++17
	-Wall
	-Wextra
	-Wformat=2
	-Werror=format
	-D CONFIG_FREERTOS_CHECK_STACKOVERFLOW=2
    -D CONFIG_FREERTOS_WATCHPOINT_END_OF_STACK	
build_src_filter = -<*> +<main.cpp> +<opendroneid.c> +<wifi.c>
monitor_speed = 230400
upload_speed = 921600
build_type = debug
monitor_filters = esp32_exception_decoder  
